name: build linux
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install LLVM and Clang 16
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '16.0.4'
          env: true

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14.1
        with:
          cmake-version: '3.27.x'

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: deps fetch dependencies
        run: go run github.com/piot/deps/src/deps@main fetch -t src/deps

      - name: create cmake cache
        run: cmake -DCMAKE_BUILD_TYPE=Debug .
        working-directory: src

      - name: build
        run: cmake --build . --clean-first -- VERBOSE=1
        working-directory: src

      #- name: run tests
      #  run: ctest --test-dir test/ --output-on-failure
      #  working-directory: src/

      - uses: actions/upload-artifact@v2
        with:
          name: Thunder Audio Buffer Linux Library
          path: |
            src/lib/libthunder-audio-buffer.a
